version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      build:
        patterns:
          - "org.apache.maven*"
          - "org.sonatype*"
      test:
        patterns:
          - "org.junit*"
          - "org.hamcrest*"
          - "org.mockito*"
          - "org.testcontainers*"
          - "org.slf4j*"
        exclude-patterns:
          - "org.springframework*"
      minor-patch:
        update-types:
          - "minor"
          - "patch"
        patterns:
          - "*"
        exclude-patterns:
          - "org.springframework*"
      spring:
        patterns:
          - "org.springframework*"
